insert into producto (nombre, precio, cantidad) values ('Cabbage Roll', 6793, 36);
insert into producto (nombre, precio, cantidad) values ('Garlic - Elephant', 2439, 48);
insert into producto (nombre, precio, cantidad) values ('Southern Comfort', 2784, 108);
insert into producto (nombre, precio, cantidad) values ('Wine - Zinfandel Rosenblum', 9970, 129);
insert into producto (nombre, precio, cantidad) values ('Wine - Red, Concha Y Toro', 2898, 9);
insert into producto (nombre, precio, cantidad) values ('Stock - Beef, White', 2031, 87);
insert into producto (nombre, precio, cantidad) values ('Clementine', 2559, 117);
insert into producto (nombre, precio, cantidad) values ('Cookie Dough - Chunky', 6086, 143);
insert into producto (nombre, precio, cantidad) values ('Garbag Bags - Black', 3716, 76);
insert into producto (nombre, precio, cantidad) values ('Thyme - Lemon, Fresh', 609, 34);
insert into producto (nombre, precio, cantidad) values ('Mix - Cocktail Strawberry Daiquiri', 6276, 69);
insert into producto (nombre, precio, cantidad) values ('Bagel - Sesame Seed Presliced', 1330, 24);
insert into producto (nombre, precio, cantidad) values ('Appetizer - Smoked Salmon / Dill', 9495, 35);
insert into producto (nombre, precio, cantidad) values ('Kellogs Raisan Bran Bars', 8166, 13);
insert into producto (nombre, precio, cantidad) values ('Hummus - Spread', 8127, 37);
insert into producto (nombre, precio, cantidad) values ('Mix - Cappucino Cocktail', 2304, 20);
insert into producto (nombre, precio, cantidad) values ('Soup - French Can Pea', 8672, 69);
insert into producto (nombre, precio, cantidad) values ('Tomatoes - Vine Ripe, Red', 6862, 155);
insert into producto (nombre, precio, cantidad) values ('Wine - Valpolicella Masi', 9242, 123);
insert into producto (nombre, precio, cantidad) values ('Chocolate - Dark Callets', 8365, 56);
insert into producto (nombre, precio, cantidad) values ('Snapple - Mango Maddness', 691, 13);
insert into producto (nombre, precio, cantidad) values ('Tortillas - Flour, 8', 2115, 113);
insert into producto (nombre, precio, cantidad) values ('Broom - Corn', 1169, 187);
insert into producto (nombre, precio, cantidad) values ('Cheese - Brick With Onion', 9449, 118);
insert into producto (nombre, precio, cantidad) values ('Island Oasis - Mango Daiquiri', 911, 41);
insert into producto (nombre, precio, cantidad) values ('Madeira', 7678, 162);
insert into producto (nombre, precio, cantidad) values ('Mushroom - Shitake, Fresh', 5905, 159);
insert into producto (nombre, precio, cantidad) values ('Tea Leaves - Oolong', 2723, 152);
insert into producto (nombre, precio, cantidad) values ('Garbag Bags - Black', 6798, 128);
insert into producto (nombre, precio, cantidad) values ('Carbonated Water - Strawberry', 1687, 57);
insert into producto (nombre, precio, cantidad) values ('Tart Shells - Savory, 4', 4209, 52);
insert into producto (nombre, precio, cantidad) values ('Cheese - Mascarpone', 8886, 29);
insert into producto (nombre, precio, cantidad) values ('Vinegar - Tarragon', 6178, 19);
insert into producto (nombre, precio, cantidad) values ('Alize Sunset', 7757, 18);
insert into producto (nombre, precio, cantidad) values ('Mushroom - Crimini', 2785, 152);
insert into producto (nombre, precio, cantidad) values ('Raisin - Dark', 4076, 20);
insert into producto (nombre, precio, cantidad) values ('Milk - Skim', 9527, 191);
insert into producto (nombre, precio, cantidad) values ('Shortbread - Cookie Crumbs', 3984, 161);
insert into producto (nombre, precio, cantidad) values ('Wine - White, Cooking', 1415, 200);
insert into producto (nombre, precio, cantidad) values ('Pancetta', 1337, 175);
insert into producto (nombre, precio, cantidad) values ('Lemonade - Strawberry, 591 Ml', 8258, 114);
insert into producto (nombre, precio, cantidad) values ('Wine - Periguita Fonseca', 3209, 100);
insert into producto (nombre, precio, cantidad) values ('Wine - Merlot Vina Carmen', 8893, 2);
insert into producto (nombre, precio, cantidad) values ('Flour - Fast / Rapid', 6452, 61);
insert into producto (nombre, precio, cantidad) values ('Sun - Dried Tomatoes', 5643, 70);
insert into producto (nombre, precio, cantidad) values ('Ham - Cooked', 7259, 157);
insert into producto (nombre, precio, cantidad) values ('Beer - Heinekin', 1900, 97);
insert into producto (nombre, precio, cantidad) values ('Pate - Peppercorn', 450, 161);
insert into producto (nombre, precio, cantidad) values ('Yogurt - Cherry, 175 Gr', 2275, 66);
insert into producto (nombre, precio, cantidad) values ('Pasta - Linguini, Dry', 4414, 137);
insert into producto (nombre, precio, cantidad) values ('Coffee Guatemala Dark', 6586, 116);
insert into producto (nombre, precio, cantidad) values ('Tomatoes - Heirloom', 1854, 33);
insert into producto (nombre, precio, cantidad) values ('Bread - Bistro Sour', 7715, 148);
insert into producto (nombre, precio, cantidad) values ('Appetizer - Shrimp Puff', 3405, 84);
insert into producto (nombre, precio, cantidad) values ('Juice - Orange 1.89l', 1978, 53);
insert into producto (nombre, precio, cantidad) values ('Sauce - Hoisin', 4570, 196);
insert into producto (nombre, precio, cantidad) values ('Pop Shoppe Cream Soda', 6539, 88);
insert into producto (nombre, precio, cantidad) values ('Wine - Barolo Fontanafredda', 1692, 93);
insert into producto (nombre, precio, cantidad) values ('Lamb Rack Frenched Australian', 1091, 83);
insert into producto (nombre, precio, cantidad) values ('Appetizer - Mango Chevre', 7805, 72);
insert into producto (nombre, precio, cantidad) values ('Pasta - Detalini, White, Fresh', 3662, 86);
insert into producto (nombre, precio, cantidad) values ('Milk - Chocolate 250 Ml', 7806, 152);
insert into producto (nombre, precio, cantidad) values ('Lemonade - Pineapple Passion', 6081, 150);
insert into producto (nombre, precio, cantidad) values ('Kellogs Special K Cereal', 132, 41);
insert into producto (nombre, precio, cantidad) values ('Duck - Legs', 6806, 124);
insert into producto (nombre, precio, cantidad) values ('Beer - Muskoka Cream Ale', 3563, 25);
insert into producto (nombre, precio, cantidad) values ('Chickhen - Chicken Phyllo', 1209, 49);
insert into producto (nombre, precio, cantidad) values ('Vinegar - Sherry', 5604, 110);
insert into producto (nombre, precio, cantidad) values ('Skewers - Bamboo', 2608, 159);
insert into producto (nombre, precio, cantidad) values ('Salmon - Atlantic, No Skin', 5890, 75);
insert into producto (nombre, precio, cantidad) values ('Lobster - Cooked', 167, 21);
insert into producto (nombre, precio, cantidad) values ('Coffee Swiss Choc Almond', 7360, 153);
insert into producto (nombre, precio, cantidad) values ('Isomalt', 9230, 173);
insert into producto (nombre, precio, cantidad) values ('Pork Loin Cutlets', 6459, 107);
insert into producto (nombre, precio, cantidad) values ('Icecream Bar - Del Monte', 5766, 174);
insert into producto (nombre, precio, cantidad) values ('Sambuca - Opal Nera', 932, 24);
insert into producto (nombre, precio, cantidad) values ('Glycerine', 2158, 173);
insert into producto (nombre, precio, cantidad) values ('Bread - Italian Roll With Herbs', 6437, 120);
insert into producto (nombre, precio, cantidad) values ('Chips - Potato Jalapeno', 7748, 169);
insert into producto (nombre, precio, cantidad) values ('Lobster - Baby, Boiled', 5292, 122);
insert into producto (nombre, precio, cantidad) values ('Shiratamako - Rice Flour', 8302, 22);
insert into producto (nombre, precio, cantidad) values ('Smirnoff Green Apple Twist', 365, 125);
insert into producto (nombre, precio, cantidad) values ('Chinese Foods - Plain Fried Rice', 4443, 191);
insert into producto (nombre, precio, cantidad) values ('Onions - Pearl', 152, 22);
insert into producto (nombre, precio, cantidad) values ('Wine - Niagara,vqa Reisling', 3567, 26);
insert into producto (nombre, precio, cantidad) values ('Easy Off Oven Cleaner', 721, 99);
insert into producto (nombre, precio, cantidad) values ('Bread - Pita, Mini', 8839, 124);
insert into producto (nombre, precio, cantidad) values ('Bar Mix - Pina Colada, 355 Ml', 5508, 99);
insert into producto (nombre, precio, cantidad) values ('Juice - Orange', 7694, 21);
insert into producto (nombre, precio, cantidad) values ('Vinegar - Red Wine', 9927, 59);
insert into producto (nombre, precio, cantidad) values ('Syrup - Monin, Swiss Choclate', 9518, 16);
insert into producto (nombre, precio, cantidad) values ('Cloves - Ground', 2581, 135);
insert into producto (nombre, precio, cantidad) values ('Red Cod Fillets - 225g', 334, 112);
insert into producto (nombre, precio, cantidad) values ('Wine - White, Ej Gallo', 4067, 42);
insert into producto (nombre, precio, cantidad) values ('Sage Ground Wiberg', 5054, 14);
insert into producto (nombre, precio, cantidad) values ('Hickory Smoke, Liquid', 9927, 10);
insert into producto (nombre, precio, cantidad) values ('Soup - Base Broth Beef', 202, 30);
insert into producto (nombre, precio, cantidad) values ('Pork - Ham Hocks - Smoked', 9697, 61);
insert into producto (nombre, precio, cantidad) values ('Absolut Citron', 5786, 2);
insert into producto (nombre, precio, cantidad) values ('Salmon - Atlantic, No Skin', 6820, 167);
